# This is a basic workflow to help you get started with Actions

name: git action secrets practice

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Print secrets
      run : echo ${{ secrets.TEST1 }} >> test.txt
    - name: print test.txt
      run : cat test.txt
    - name: Print Secrets
      run: |
        echo "List of Secrets:"
        for key in ${{ secrets.keys }}; do
         echo "- $key" >> test.sh
        done
    - name: cat file
      run: cat test.sh
    - name: ls file
      run: ls -alh | grep test
